### PR TITLE
fix(build): use .module.js instead of .mjs for esm bundle, closes #331

### LINKED ISSUE #331: react native can not recognize `.mjs` file
error: bundling failed: Error: While trying to resolve module `immer` from file `/Users/.../src/reducers/uiStateReducer.ts`, the package `/Users/.../node_modules/immer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/.../node_modules/immer/dist/immer.mjs`.

Related to https://github.com/mweststrate/immer/commit/b9f0029bf77a7ab993133551a635680b559c7532#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

### PR DESCRIPTION
**Pull request by egoist**
closes #331

### CODE REVIEW

**Comment by mweststrate** [comment]
Could you give some background why the extension difference matters?

**Comment by egoist** [comment]
@mweststrate metro bundler doesn't support `.mjs` yet, it will try to resolve `immer/dist/immer.mjs(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`

**Comment by aleclarson** [comment]
Thanks @egoist! ❤️

**Pull request merged**
