### PR TITLE
chore: replace rollup with bili

### PR DESCRIPTION
**Pull request by egoist**
This is a follow-up PR to #247

Changes:

- Output ESM bundle to `dist/immer.mjs`
- Using buble instead of babel-preset-env for smaller output

### CODE REVIEW

**Comment by egoist** [comment]
Somehow the node 8 job failed

**Comment by aleclarson** [comment]
> hmmm Travis is really slow 😅 CircleCI can finish the same tests in 30 seconds

Oh so *that's* why people use CircleCI. 😆 

Now the Node 6 build is saying:
```
$ /home/travis/build/mweststrate/immer/node_modules/.bin/bili
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected identifier
```
Yet it still passes. 😳

**Comment by aleclarson** [comment]
Aww, just realized that Bublé does not support `static` class properties, which are used in #305. 😢

**Comment by egoist** [comment]
@aleclarson you can still add Babel plugins, Bublé is just used to replace babel-preset-env

**Comment by aleclarson** [comment]
@egoist Interesting! I'm surprised that actually improves performance, since you're then parsing the AST twice (and still using Babel's code generator) if I understand correctly.

**Comment by egoist** [comment]
The unhandled promise rejection is gone now.

**Pull request merged**
