### PR TITLE
Add TypeScript Mapped Draft Type

### LINKED ISSUE #97: [TypeScript] Produced draft is read-only if original state is read-only
The `draft` returned by the `produce` function's callback should make a mutable clone from the original state. Currently immutability is retained:

```ts
interface IState {
  readonly foo: boolean;
}

const state: IState = {
  foo: false
};

produce(state, draft => {
  draft.foo = true; // Error: Cannot assign to 'foo' because it is a constant or a read-only property.
});
```

### PR DESCRIPTION
**Pull request by knpwrs**
These changes enable the following:

```ts
import produce from 'immer';
 
interface State {
  readonly x: number;
}
 
// `x` cannot be modified here
const state: State = {
  x: 0;
};
 
const newState = produce<State>((draft) => {
  // `x` can be modified here
  draft.x++;
});
 
// `newState.x` cannot be modified here
```

This helps TypeScript users ensure immutability of their state interfaces. I had to upgrade TypeScript for the `index.d.ts` file to parse properly. This feature was merged into TypeScript back in February: https://github.com/Microsoft/TypeScript/pull/21919

~~It also appears that the `flow/ts.ts` file doesn't run and never did. I tested this externally and it works, but I'd like to see a more robust test suite in this repo.~~

**EDIT:** I've added some TypeScript tests in Jest.

**EDIT:** Fixes #97

### CODE REVIEW

**Comment by knpwrs** [comment]
Looks like everything is working now. All of the following compiles and works as expected:

```ts
import produce from 'immer';

interface State {
  readonly num: number;
  readonly foo?: string;
  bar: string;
  readonly baz: {
    readonly x: number;
    readonly y: number;
  };
  readonly arr: ReadonlyArray<{ readonly value: string }>;
  readonly arr2: { readonly value: string }[];
}

const state: State = {
  num: 0,
  bar: 'foo',
  baz: {
    x: 1,
    y: 2,
  },
  arr: [{ value: 'asdf' }],
  arr2: [{ value: 'asdf' }],
}

const newState = produce<State>(draft => {
  draft.num++;
  draft.foo = 'bar';
  draft.bar = 'foo';
  draft.baz.x++;
  draft.baz.y++;
  draft.arr[0].value = 'foo';
  draft.arr.push({ value: 'asf' });
  draft.arr2[0].value = 'foo';
  draft.arr2.push({ value: 'asf' });
})(state);
```

**Comment by knpwrs** [comment]
I only just now noticed the previous discussions in #97 and #109. I believe what I have here is a solution that fixes #97 and addresses the problems in #109.

**Comment by andrea-smartsailors** [comment]
This would be really useful to us, thank you very much @knpwrs

**Comment by knpwrs** [comment]
@mweststrate is there any interest from the project owners to add these typings?

**Comment by mweststrate** [comment]
Yes; but didn't get to reviewing yet 😊

Op za 23 jun. 2018 19:42 schreef Ken Powers <notifications@github.com>:

**Comment by andrea-smartsailors** [comment]
Hello @mweststrate 
+1 for this PR from my side :grinning: :+1:

**Comment by mweststrate** [comment]
Reviewed! No comments, looks awesome :). Will release next week

**Pull request merged**
