### PR TITLE
Fix typo in state tree image

### PR DESCRIPTION
**Pull request by jkhedani**
Updated the image with the typo correction and double-checked spelling on all the other images.  Luckily, you won't need to redo the awesome 3D version you made as the typo is well below the crop. Apologies - I didn't mean to take up too much of your time with this!

### CODE REVIEW

**Comment by mweststrate** [comment]
No worries, I should have spotted it as well (but I am notoriously bad at spotting spelling errors)

**Comment by mweststrate** [comment]
If there is ever another revision, you could drop one of the leaf red dots; not all proxies have to have modifications. But that is so subtle, don't fill obliged to change that

**Comment by mweststrate** [comment]
Blog post is updated

**Comment by jkhedani** [comment]
Ah, yup. No worries - I'll make the edit and submit another pull request.

**Pull request merged**
