### PR TITLE
invalidate the proxy of the base state after immer function executes

### LINKED ISSUE #10: Make sure all proxies die after immer func ends
Protects people against accidentally using proxies in async fashion etc

### PR DESCRIPTION
**Pull request by benbraou**
1. Using a revocable proxy instead of a proxy, we invalidate the proxy when immer function executes
1. I used jsdoc @typedef, but I can create an internal typescript definition file and reference it in immer. js if needed

Fixes #10

### CODE REVIEW

**Comment by mweststrate** [comment]
Hey, Thanks for the PR! Really appreciate it.

Some remarks. I think the PR can be improved in the following way:
1. revoke all the proxies in the `proxies` map. This protects users from passing a (part of) the tree to an async process for example.
2. I would keep the signature of `createProxy` as is, keep the short name and just return the proxy. But, in the `proxies` map store the entire struct to be able to revoke them later on. 

Does that make sense?

I just created a PR for auto-freezing and supporting already frozen trees (that was less trivial then I hoped for). Would you be interested in reviewing it? #15 

Thanks for your contributions!

**Comment by benbraou** [comment]
@mweststrate Thanks for the review! Indeed, that makes sense. I will update my PR accordingly by tomorrow.
Yes, I am interested in reviewing #15 . That will be educational for me. Thanks!

**Comment by benbraou** [comment]
Pull request update as requested. Happy new year!

**Comment by mweststrate** [comment]
Thanks a lot @benbraou !

**Pull request merged**
