### PR TITLE
New README image

### PR DESCRIPTION
**Pull request by jkhedani**
Made a sweet new graphic for the README. Let me know if you want me to make changes or if you'd like me to also do the others in the same style.

If you were going for that just-illustrated, hand-drawn look, please forgive my ignorance.

### CODE REVIEW

**Comment by mweststrate** [comment]
Fonts are a bit small. Further looking good, thanks! Feel free to update the others as well😀

**Comment by jkhedani** [comment]
@mweststrate Agreed on the font size. Updated and it looks OK on mobile. Also, updated the other graphics for your review. I've mocked them up in your Medium post to give you a better idea of how it might look on screen:

immer-medium-2
immer-medium

**Comment by mweststrate** [comment]
Awesome, those look great! Thanks a lot

**Comment by mweststrate** [comment]
Update blog, thanks!

Op vr 12 jan. 2018 om 05:43 schreef Justin Hedani <notifications@github.com

**Comment by jkhedani** [comment]
Awesome - glad you liked them!

**Comment by arthurdenner** [comment]
@jkhedani, beautiful images. I just wanted to point out a typo in "modified proxy". Sorry for the inconvenience.

**Comment by jkhedani** [comment]
@arthurdenner No worries - thanks for the spot! I've fixed the typo and created a new pull request. I think the only inconvenience will be that mwestrate will have to update the Medium article with which this image was for :(

**Pull request merged**
