### PR TITLE
feat: export `setHook` function

### PR DESCRIPTION
**Pull request by aleclarson**
Adds the following hooks:

- `setProperty(draftState, prop, newValue)`
- `deleteProperty(draftState, prop)`
- `copyObject(draftState)`

```ts
import {setHook} from 'immer'

setHook('setProperty', (state, prop, newValue) => {
  console.log(prop, '=', newValue)
})
```

Currently, `setHook` can only be called **once** per hook.

These hooks are nice for tracking copies and changed properties.

### CODE REVIEW

**Comment by mweststrate** [comment]
I'm currently preparing for a conf, so postponing on reviewing, non-trivial MRs, will get back at this in two weeks!

**Comment by mweststrate** [comment]
The goal of this PR is unclear to me :)

**Comment by aleclarson** [comment]
@mweststrate Provide hooks for other packages to use. These are intended for library authors. They could also be used for some kind of Immer debugger, if anyone ever finds a reason for doing so. ;)

**Comment by aleclarson** [comment]
Bummed we couldn't fit this into v1.8.0 :(

**Comment by aleclarson** [comment]
I have two packages in the works where it's crucial (perf-wise) for them to plug into Immer's draft processing phase. If this PR isn't merged, they'll be forced to traverse every `produce`-returned copy manually and they would miss out on the rich metadata provided by draft objects. 💯 🔥

**Comment by aleclarson** [comment]
Closed in favor of #258

@mweststrate When the libraries are ready, I will point you to where I'm using Immer hooks.

**Comment by aleclarson** [comment]
@mweststrate I'm not really sold on the "unsafe_" prefix rationale. If the contract needs amendment, publish a major version. Why not? You could even do a pre-release if you want to gather feedback before finalizing the API. This way, you're not threatening users of the API with breakage for (seemingly) no reason.

**Pull request closed without merging**
