### PR TITLE
added coveralls and updated readme 

### LINKED ISSUE #7: Add Travis, batches, coverage, cdn, umd build and such
- [x] Travis added with f895e016dd4c3374fe5e7f95ff4d642dffbb0367  _thanks @Gregjarvez_
- [ ] batches
- [ ] test coverage
- [ ] cdn 
- [ ] umd build

### PR DESCRIPTION
**Pull request by Gregjarvez**
badge url has been updated to point to @mweststrate master

`.coverall.yml ` key needs to point to your repo as well. currently has mine
fixes #7

### CODE REVIEW

**Comment by mweststrate** [comment]
@Gregjarvez thanks! Could you remove the package-lock file? Current setup uses yarn so that will be confusing

**Comment by Gregjarvez** [comment]
Need I worry about the conflicts ? @mweststrate

**Comment by Gregjarvez** [comment]
@mweststrate  I am adding the donate badge today once I get time. should I use a placeholder link?

**Comment by mweststrate** [comment]
You can link it for now to https://mobx.js.org/donate.html

**Comment by mweststrate** [comment]
Don't worry about the conflicts, I'll solve them when merging

**Comment by mweststrate** [comment]
Thanks!

**Pull request merged**
