### PR TITLE
Add incremental benchmark

### PR DESCRIPTION
**Pull request by scriby**
For #138

### CODE REVIEW

**Comment by scriby** [comment]
Here are the benchmark results on my machine:

 PASS  __performance_tests__/incremental.js (5.342s)
  Incremental performance
    ✓ just mutate (3ms)
    ✓ handcrafted reducer (no freeze) (1912ms)
    ✓ immutableJS (39ms)
    ✓ immer (proxy) - without autofreeze (2365ms)

**Comment by mweststrate** [comment]
Sorry for not following up yet, definitely thanks for the contribution. Could you add two tests for the full picture: immer in ES5 mode, and immutableJS including a toJS() at the end (I think that is a fairer comparision as in the end in most application stuff has to be toJS-ed, for example during rendering or network requests)

**Comment by scriby** [comment]
No problem adding the ES5 version, but from what I can see I don't think the ImmutableJS.toJS test represents any realistic use case. Serializing back to JS after every action completely defeats the performance gains (and purpose) of using ImmutableJS to begin with.

In most cases, we would just be grabbing individual items out of the ImmutableJS collection, which has negligible overhead. In the case that we want all the items, the best bet would be to iterate over the collection, which is much cheaper than toJS because it can use the items themselves as-is. Perhaps a more realistic benchmark would be to perform all the state changes and then grab some items or iterate over the whole collection?

Based on my understanding of Immer, because it needs to retain immutability of the state, it is basically forced to copy the modified arrays/maps on each update, which is very similar to hand crafted reducers. I think the solution for Immer is similar to the solution for regular redux, which would be something like ImmutableJS, but usable with Immer.

I've actually started hacking on that concept here: https://github.com/scriby/immerutable. Right now I'm working on a Map based on a trie which is very similar to ImmutableJS's one, and a btree for maintaining a collection in sorted order (which ImmutableJS doesn't have an equivalent of). For the same workload as this benchmark, Immerutable is at about 130ms. I'm a couple weeks from finishing/polishing it up, but I think it's looking promising.

Thanks for taking a look,

Chris

**Comment by jurosh** [comment]
Yea I must agree with @scriby, that in real world apps you don't want to ever do `toJS` or `fromJS` as those are most expensive operations. Generally you just work with Immutable pushing there values and iterating still as Immutable without need to wrap/unwrap it.

**Pull request merged**
