### PR TITLE
feat: export `isDraft` function

### PR DESCRIPTION
**Pull request by aleclarson**
To use in other libraries

### CODE REVIEW

**Comment by aleclarson** [comment]
I guess you *could* do `!!original(value)` to get the same effect as `isDraft(value)`. WDYT?

**Comment by mweststrate** [comment]
Should isDraft return true for a new object that was added to the draft
tree? Probably not?

Op vr 19 okt. 2018 20:51 schreef Alec Larson <notifications@github.com>:

**Comment by aleclarson** [comment]
@mweststrate "Just proxies" is the idea. LGTM?

**Comment by mweststrate** [comment]
@aleclarson LGTM. Could you add some tests for both proxy and non proxied version?

**Comment by aleclarson** [comment]
Are tests necessary? It's a very simple function: `const isDraft = (value) => !!value && !!value[PROXY_STATE]`

**Comment by mweststrate** [comment]
For regression against internal refactorings, yeah please provide a some
false and positive tests to protect against accidental mistakes.

Op zo 21 okt. 2018 12:34 schreef Alec Larson <notifications@github.com>:

**Comment by aleclarson** [comment]
Done!

**Pull request merged**
